### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [bob-reus/octave-mirbeau_calvary_louis-rich#1]
# General Issues:

- [x] We don't change hyphens to spaces or vice versa that are not changed by `modernize-spelling`.  You need to revert commits `[Editorial] red hot -> red-hot`, `[Editorial] galley-slave -> galley slave`, and `[Editorial] terra cotta -> terra-cotta`.

**Comment by bob-reus** [comment]
I've reverted these three commits. Would you like me to go over the changes in `[Editorial] modernize spelling (add/remove dashes, spaces according to MW)` as well?

**Comment by EmmaSweeney** [comment]
You can revert those changes too.

**Comment by bob-reus** [comment]
Thanks, I've gone over the commit and reverted the words where dashes were replaced by spaces and vice versa.
